

export const GET_POKEMON_HERO = 'GET_POKEMON_HERO';
export const GET_POKEMON_CAROUSEL = 'GET_POKEMON_CAROUSEL';
export const GET_POKEDEX = 'GET_POKEDEX';

export const SET_LOADING_POKEMONS_CAROUSEL = 'SET_LOADING_POKEMON_CAROUSEL';
export const SET_LOADING_POKEMONS_HERO = 'SET_LOADING_POKEMON_HERO';
export const SET_LOADING_POKEDEX = 'SET_LOADING_POKEDEX';
export const ERROR_POKEDEX = 'ERROR';
